name: Test Health Checker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Make script executable
        run: chmod +x health-check.sh
      
      - name: Run health check
        run: ./health-check.sh
      
      - name: Verify log file created
        run: ls -lh health-check-*.log
      
      - name: Show log contents
        run: cat health-check-*.log
